### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [rhysd/Crisp#3]
Hello,

I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date. Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by Archivist062** [comment]
> I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date.

I made a manual test and the project builds and runs on Fedora with Crystal 0.26.1 and have working specs

**Comment by rhysd** [comment]
This was a project to learn how to create dynamic language interpreter for me. So I don't build this project so frequently and cannot notice it's broken due to Crystal compiler updates. However, when I receive an issue (and I have time to fix), of course I'll try to fix this project.

**Comment by rhysd** [comment]
I tried to build project with `crystal build crisp.cr` and it looks working fine.

![2018-09-20 19 57 04](https://user-images.githubusercontent.com/823277/45813885-d2492180-bd0e-11e8-8665-b7161e77fd31.png)

`crystal --version`:

```
Crystal 0.26.1 (2018-08-27)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

**Comment by vladfaust** [comment]
Alright, sorry for disturbing! Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build starts to fail: https://docs.travis-ci.com/user/cron-jobs.

Thanks.

**Comment by rhysd** [comment]
@vladfaus Please never mind. Thank you for making the CI system. It also looks helpful for me.
